### ISSUE TITLE
explanation request: how fast_io faster than cstdio 

### ISSUE THREAD

**Issue by iamnotagentleman** [expnkx/fast_io#2]
a explanation about why fast_io faster than ctsdio and which c++20 concepts used ?

**Comment by expnkx** [comment]
Because it provides a correct protocol among different layers of the component to run fast.

For example
https://github.com/expnkx/fast_io/blob/master/include/fast_io_core_impl/print_scan.h#L287

It will first check whether it is a mutex stream. If it is, it will lock the stream and get its unlocked handle. Then it checks whether it can directly get printed or whether the stream has a buffer, if it does, it will print data to buffer directly. Or it will use a temporary buffer, write all your data to an output stream and then flush out.

Same thing with the zero-copy transmission.
inline constexpr auto transmit_impl(output& outp,input& inp,Args&& ...args)

**Comment by expnkx** [comment]
You can read wikis to get a basic understanding of the I/O library
https://github.com/expnkx/fast_io/wiki

**Comment by expnkx** [comment]
1. You only have 3 buffer pointers + 1 OS handle in I/O buffer.
2. Carefully testing buffer size with different benchmarks.
3. Pick the highest performance algorithms.
4. Do in-place formatting.
5. Everything is now inlined or even constexpr.

**Comment by iamnotagentleman** [comment]
Thanks for help 💯
